easy_admin:
        entities:
            Recipe:
                class: App\Entity\Recipe
                templates:
                    edit: 'admin/recipe/edit.html.twig'
                list:
                  actions:
                      - {name: "edit", icon: "pencil", label: false, css_class: "btn btn-primary mb-2"}
                      - {name: "delete", icon: "trash", label: false, css_class: "btn btn-danger"}